/*
 * Copyright (C) 2016  Leo Gaspard
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

use serde::{de, Deserialize, Deserializer, Serialize, Serializer};

#[allow(non_camel_case_types)]
#[derive(PartialEq, Eq, Clone, Copy, Debug, Hash)]
pub enum Syscall {
    read = 0,
    write = 1,
    open = 2,
    close = 3,
    stat = 4,
    fstat = 5,
    lstat = 6,
    poll = 7,
    lseek = 8,
    mmap = 9,
    mprotect = 10,
    munmap = 11,
    brk = 12,
    rt_sigaction = 13,
    rt_sigprocmask = 14,
    rt_sigreturn = 15,
    ioctl = 16,
    pread64 = 17,
    pwrite64 = 18,
    readv = 19,
    writev = 20,
    access = 21,
    pipe = 22,
    select = 23,
    sched_yield = 24,
    mremap = 25,
    msync = 26,
    mincore = 27,
    madvise = 28,
    shmget = 29,
    shmat = 30,
    shmctl = 31,
    dup = 32,
    dup2 = 33,
    pause = 34,
    nanosleep = 35,
    getitimer = 36,
    alarm = 37,
    setitimer = 38,
    getpid = 39,
    sendfile = 40,
    socket = 41,
    connect = 42,
    accept = 43,
    sendto = 44,
    recvfrom = 45,
    sendmsg = 46,
    recvmsg = 47,
    shutdown = 48,
    bind = 49,
    listen = 50,
    getsockname = 51,
    getpeername = 52,
    socketpair = 53,
    setsockopt = 54,
    getsockopt = 55,
    clone = 56,
    fork = 57,
    vfork = 58,
    execve = 59,
    exit = 60,
    wait4 = 61,
    kill = 62,
    uname = 63,
    semget = 64,
    semop = 65,
    semctl = 66,
    shmdt = 67,
    msgget = 68,
    msgsnd = 69,
    msgrcv = 70,
    msgctl = 71,
    fcntl = 72,
    flock = 73,
    fsync = 74,
    fdatasync = 75,
    truncate = 76,
    ftruncate = 77,
    getdents = 78,
    getcwd = 79,
    chdir = 80,
    fchdir = 81,
    rename = 82,
    mkdir = 83,
    rmdir = 84,
    creat = 85,
    link = 86,
    unlink = 87,
    symlink = 88,
    readlink = 89,
    chmod = 90,
    fchmod = 91,
    chown = 92,
    fchown = 93,
    lchown = 94,
    umask = 95,
    gettimeofday = 96,
    getrlimit = 97,
    getrusage = 98,
    sysinfo = 99,
    times = 100,
    ptrace = 101,
    getuid = 102,
    syslog = 103,
    getgid = 104,
    setuid = 105,
    setgid = 106,
    geteuid = 107,
    getegid = 108,
    setpgid = 109,
    getppid = 110,
    getpgrp = 111,
    setsid = 112,
    setreuid = 113,
    setregid = 114,
    getgroups = 115,
    setgroups = 116,
    setresuid = 117,
    getresuid = 118,
    setresgid = 119,
    getresgid = 120,
    getpgid = 121,
    setfsuid = 122,
    setfsgid = 123,
    getsid = 124,
    capget = 125,
    capset = 126,
    rt_sigpending = 127,
    rt_sigtimedwait = 128,
    rt_sigqueueinfo = 129,
    rt_sigsuspend = 130,
    sigaltstack = 131,
    utime = 132,
    mknod = 133,
    uselib = 134,
    personality = 135,
    ustat = 136,
    statfs = 137,
    fstatfs = 138,
    sysfs = 139,
    getpriority = 140,
    setpriority = 141,
    sched_setparam = 142,
    sched_getparam = 143,
    sched_setscheduler = 144,
    sched_getscheduler = 145,
    sched_get_priority_max = 146,
    sched_get_priority_min = 147,
    sched_rr_get_interval = 148,
    mlock = 149,
    munlock = 150,
    mlockall = 151,
    munlockall = 152,
    vhangup = 153,
    modify_ldt = 154,
    pivot_root = 155,
    _sysctl = 156,
    prctl = 157,
    arch_prctl = 158,
    adjtimex = 159,
    setrlimit = 160,
    chroot = 161,
    sync = 162,
    acct = 163,
    settimeofday = 164,
    mount = 165,
    umount2 = 166,
    swapon = 167,
    swapoff = 168,
    reboot = 169,
    sethostname = 170,
    setdomainname = 171,
    iopl = 172,
    ioperm = 173,
    create_module = 174,
    init_module = 175,
    delete_module = 176,
    get_kernel_syms = 177,
    query_module = 178,
    quotactl = 179,
    nfsservctl = 180,
    getpmsg = 181,
    putpmsg = 182,
    afs_syscall = 183,
    tuxcall = 184,
    security = 185,
    gettid = 186,
    readahead = 187,
    setxattr = 188,
    lsetxattr = 189,
    fsetxattr = 190,
    getxattr = 191,
    lgetxattr = 192,
    fgetxattr = 193,
    listxattr = 194,
    llistxattr = 195,
    flistxattr = 196,
    removexattr = 197,
    lremovexattr = 198,
    fremovexattr = 199,
    tkill = 200,
    time = 201,
    futex = 202,
    sched_setaffinity = 203,
    sched_getaffinity = 204,
    set_thread_area = 205,
    io_setup = 206,
    io_destroy = 207,
    io_getevents = 208,
    io_submit = 209,
    io_cancel = 210,
    get_thread_area = 211,
    lookup_dcookie = 212,
    epoll_create = 213,
    epoll_ctl_old = 214,
    epoll_wait_old = 215,
    remap_file_pages = 216,
    getdents64 = 217,
    set_tid_address = 218,
    restart_syscall = 219,
    semtimedop = 220,
    fadvise64 = 221,
    timer_create = 222,
    timer_settime = 223,
    timer_gettime = 224,
    timer_getoverrun = 225,
    timer_delete = 226,
    clock_settime = 227,
    clock_gettime = 228,
    clock_getres = 229,
    clock_nanosleep = 230,
    exit_group = 231,
    epoll_wait = 232,
    epoll_ctl = 233,
    tgkill = 234,
    utimes = 235,
    vserver = 236,
    mbind = 237,
    set_mempolicy = 238,
    get_mempolicy = 239,
    mq_open = 240,
    mq_unlink = 241,
    mq_timedsend = 242,
    mq_timedreceive = 243,
    mq_notify = 244,
    mq_getsetattr = 245,
    kexec_load = 246,
    waitid = 247,
    add_key = 248,
    request_key = 249,
    keyctl = 250,
    ioprio_set = 251,
    ioprio_get = 252,
    inotify_init = 253,
    inotify_add_watch = 254,
    inotify_rm_watch = 255,
    migrate_pages = 256,
    openat = 257,
    mkdirat = 258,
    mknodat = 259,
    fchownat = 260,
    futimesat = 261,
    newfstatat = 262,
    unlinkat = 263,
    renameat = 264,
    linkat = 265,
    symlinkat = 266,
    readlinkat = 267,
    fchmodat = 268,
    faccessat = 269,
    pselect6 = 270,
    ppoll = 271,
    unshare = 272,
    set_robust_list = 273,
    get_robust_list = 274,
    splice = 275,
    tee = 276,
    sync_file_range = 277,
    vmsplice = 278,
    move_pages = 279,
    utimensat = 280,
    epoll_pwait = 281,
    signalfd = 282,
    timerfd_create = 283,
    eventfd = 284,
    fallocate = 285,
    timerfd_settime = 286,
    timerfd_gettime = 287,
    accept4 = 288,
    signalfd4 = 289,
    eventfd2 = 290,
    epoll_create1 = 291,
    dup3 = 292,
    pipe2 = 293,
    inotify_init1 = 294,
    preadv = 295,
    pwritev = 296,
    rt_tgsigqueueinfo = 297,
    perf_event_open = 298,
    recvmmsg = 299,
    fanotify_init = 300,
    fanotify_mark = 301,
    prlimit64 = 302,
    name_to_handle_at = 303,
    open_by_handle_at = 304,
    clock_adjtime = 305,
    syncfs = 306,
    sendmmsg = 307,
    setns = 308,
    getcpu = 309,
    process_vm_readv = 310,
    process_vm_writev = 311,
    kcmp = 312,
    finit_module = 313,
    sched_setattr = 314,
    sched_getattr = 315,
    renameat2 = 316,
    seccomp = 317,
    getrandom = 318,
    memfd_create = 319,
    kexec_file_load = 320,
    bpf = 321,
    execveat = 322,
    userfaultfd = 323,
    membarrier = 324,
    mlock2 = 325,
}

pub fn from(x: u64) -> Option<Syscall> {
    match x {
        0 => Some(Syscall::read),
        1 => Some(Syscall::write),
        2 => Some(Syscall::open),
        3 => Some(Syscall::close),
        4 => Some(Syscall::stat),
        5 => Some(Syscall::fstat),
        6 => Some(Syscall::lstat),
        7 => Some(Syscall::poll),
        8 => Some(Syscall::lseek),
        9 => Some(Syscall::mmap),
        10 => Some(Syscall::mprotect),
        11 => Some(Syscall::munmap),
        12 => Some(Syscall::brk),
        13 => Some(Syscall::rt_sigaction),
        14 => Some(Syscall::rt_sigprocmask),
        15 => Some(Syscall::rt_sigreturn),
        16 => Some(Syscall::ioctl),
        17 => Some(Syscall::pread64),
        18 => Some(Syscall::pwrite64),
        19 => Some(Syscall::readv),
        20 => Some(Syscall::writev),
        21 => Some(Syscall::access),
        22 => Some(Syscall::pipe),
        23 => Some(Syscall::select),
        24 => Some(Syscall::sched_yield),
        25 => Some(Syscall::mremap),
        26 => Some(Syscall::msync),
        27 => Some(Syscall::mincore),
        28 => Some(Syscall::madvise),
        29 => Some(Syscall::shmget),
        30 => Some(Syscall::shmat),
        31 => Some(Syscall::shmctl),
        32 => Some(Syscall::dup),
        33 => Some(Syscall::dup2),
        34 => Some(Syscall::pause),
        35 => Some(Syscall::nanosleep),
        36 => Some(Syscall::getitimer),
        37 => Some(Syscall::alarm),
        38 => Some(Syscall::setitimer),
        39 => Some(Syscall::getpid),
        40 => Some(Syscall::sendfile),
        41 => Some(Syscall::socket),
        42 => Some(Syscall::connect),
        43 => Some(Syscall::accept),
        44 => Some(Syscall::sendto),
        45 => Some(Syscall::recvfrom),
        46 => Some(Syscall::sendmsg),
        47 => Some(Syscall::recvmsg),
        48 => Some(Syscall::shutdown),
        49 => Some(Syscall::bind),
        50 => Some(Syscall::listen),
        51 => Some(Syscall::getsockname),
        52 => Some(Syscall::getpeername),
        53 => Some(Syscall::socketpair),
        54 => Some(Syscall::setsockopt),
        55 => Some(Syscall::getsockopt),
        56 => Some(Syscall::clone),
        57 => Some(Syscall::fork),
        58 => Some(Syscall::vfork),
        59 => Some(Syscall::execve),
        60 => Some(Syscall::exit),
        61 => Some(Syscall::wait4),
        62 => Some(Syscall::kill),
        63 => Some(Syscall::uname),
        64 => Some(Syscall::semget),
        65 => Some(Syscall::semop),
        66 => Some(Syscall::semctl),
        67 => Some(Syscall::shmdt),
        68 => Some(Syscall::msgget),
        69 => Some(Syscall::msgsnd),
        70 => Some(Syscall::msgrcv),
        71 => Some(Syscall::msgctl),
        72 => Some(Syscall::fcntl),
        73 => Some(Syscall::flock),
        74 => Some(Syscall::fsync),
        75 => Some(Syscall::fdatasync),
        76 => Some(Syscall::truncate),
        77 => Some(Syscall::ftruncate),
        78 => Some(Syscall::getdents),
        79 => Some(Syscall::getcwd),
        80 => Some(Syscall::chdir),
        81 => Some(Syscall::fchdir),
        82 => Some(Syscall::rename),
        83 => Some(Syscall::mkdir),
        84 => Some(Syscall::rmdir),
        85 => Some(Syscall::creat),
        86 => Some(Syscall::link),
        87 => Some(Syscall::unlink),
        88 => Some(Syscall::symlink),
        89 => Some(Syscall::readlink),
        90 => Some(Syscall::chmod),
        91 => Some(Syscall::fchmod),
        92 => Some(Syscall::chown),
        93 => Some(Syscall::fchown),
        94 => Some(Syscall::lchown),
        95 => Some(Syscall::umask),
        96 => Some(Syscall::gettimeofday),
        97 => Some(Syscall::getrlimit),
        98 => Some(Syscall::getrusage),
        99 => Some(Syscall::sysinfo),
        100 => Some(Syscall::times),
        101 => Some(Syscall::ptrace),
        102 => Some(Syscall::getuid),
        103 => Some(Syscall::syslog),
        104 => Some(Syscall::getgid),
        105 => Some(Syscall::setuid),
        106 => Some(Syscall::setgid),
        107 => Some(Syscall::geteuid),
        108 => Some(Syscall::getegid),
        109 => Some(Syscall::setpgid),
        110 => Some(Syscall::getppid),
        111 => Some(Syscall::getpgrp),
        112 => Some(Syscall::setsid),
        113 => Some(Syscall::setreuid),
        114 => Some(Syscall::setregid),
        115 => Some(Syscall::getgroups),
        116 => Some(Syscall::setgroups),
        117 => Some(Syscall::setresuid),
        118 => Some(Syscall::getresuid),
        119 => Some(Syscall::setresgid),
        120 => Some(Syscall::getresgid),
        121 => Some(Syscall::getpgid),
        122 => Some(Syscall::setfsuid),
        123 => Some(Syscall::setfsgid),
        124 => Some(Syscall::getsid),
        125 => Some(Syscall::capget),
        126 => Some(Syscall::capset),
        127 => Some(Syscall::rt_sigpending),
        128 => Some(Syscall::rt_sigtimedwait),
        129 => Some(Syscall::rt_sigqueueinfo),
        130 => Some(Syscall::rt_sigsuspend),
        131 => Some(Syscall::sigaltstack),
        132 => Some(Syscall::utime),
        133 => Some(Syscall::mknod),
        134 => Some(Syscall::uselib),
        135 => Some(Syscall::personality),
        136 => Some(Syscall::ustat),
        137 => Some(Syscall::statfs),
        138 => Some(Syscall::fstatfs),
        139 => Some(Syscall::sysfs),
        140 => Some(Syscall::getpriority),
        141 => Some(Syscall::setpriority),
        142 => Some(Syscall::sched_setparam),
        143 => Some(Syscall::sched_getparam),
        144 => Some(Syscall::sched_setscheduler),
        145 => Some(Syscall::sched_getscheduler),
        146 => Some(Syscall::sched_get_priority_max),
        147 => Some(Syscall::sched_get_priority_min),
        148 => Some(Syscall::sched_rr_get_interval),
        149 => Some(Syscall::mlock),
        150 => Some(Syscall::munlock),
        151 => Some(Syscall::mlockall),
        152 => Some(Syscall::munlockall),
        153 => Some(Syscall::vhangup),
        154 => Some(Syscall::modify_ldt),
        155 => Some(Syscall::pivot_root),
        156 => Some(Syscall::_sysctl),
        157 => Some(Syscall::prctl),
        158 => Some(Syscall::arch_prctl),
        159 => Some(Syscall::adjtimex),
        160 => Some(Syscall::setrlimit),
        161 => Some(Syscall::chroot),
        162 => Some(Syscall::sync),
        163 => Some(Syscall::acct),
        164 => Some(Syscall::settimeofday),
        165 => Some(Syscall::mount),
        166 => Some(Syscall::umount2),
        167 => Some(Syscall::swapon),
        168 => Some(Syscall::swapoff),
        169 => Some(Syscall::reboot),
        170 => Some(Syscall::sethostname),
        171 => Some(Syscall::setdomainname),
        172 => Some(Syscall::iopl),
        173 => Some(Syscall::ioperm),
        174 => Some(Syscall::create_module),
        175 => Some(Syscall::init_module),
        176 => Some(Syscall::delete_module),
        177 => Some(Syscall::get_kernel_syms),
        178 => Some(Syscall::query_module),
        179 => Some(Syscall::quotactl),
        180 => Some(Syscall::nfsservctl),
        181 => Some(Syscall::getpmsg),
        182 => Some(Syscall::putpmsg),
        183 => Some(Syscall::afs_syscall),
        184 => Some(Syscall::tuxcall),
        185 => Some(Syscall::security),
        186 => Some(Syscall::gettid),
        187 => Some(Syscall::readahead),
        188 => Some(Syscall::setxattr),
        189 => Some(Syscall::lsetxattr),
        190 => Some(Syscall::fsetxattr),
        191 => Some(Syscall::getxattr),
        192 => Some(Syscall::lgetxattr),
        193 => Some(Syscall::fgetxattr),
        194 => Some(Syscall::listxattr),
        195 => Some(Syscall::llistxattr),
        196 => Some(Syscall::flistxattr),
        197 => Some(Syscall::removexattr),
        198 => Some(Syscall::lremovexattr),
        199 => Some(Syscall::fremovexattr),
        200 => Some(Syscall::tkill),
        201 => Some(Syscall::time),
        202 => Some(Syscall::futex),
        203 => Some(Syscall::sched_setaffinity),
        204 => Some(Syscall::sched_getaffinity),
        205 => Some(Syscall::set_thread_area),
        206 => Some(Syscall::io_setup),
        207 => Some(Syscall::io_destroy),
        208 => Some(Syscall::io_getevents),
        209 => Some(Syscall::io_submit),
        210 => Some(Syscall::io_cancel),
        211 => Some(Syscall::get_thread_area),
        212 => Some(Syscall::lookup_dcookie),
        213 => Some(Syscall::epoll_create),
        214 => Some(Syscall::epoll_ctl_old),
        215 => Some(Syscall::epoll_wait_old),
        216 => Some(Syscall::remap_file_pages),
        217 => Some(Syscall::getdents64),
        218 => Some(Syscall::set_tid_address),
        219 => Some(Syscall::restart_syscall),
        220 => Some(Syscall::semtimedop),
        221 => Some(Syscall::fadvise64),
        222 => Some(Syscall::timer_create),
        223 => Some(Syscall::timer_settime),
        224 => Some(Syscall::timer_gettime),
        225 => Some(Syscall::timer_getoverrun),
        226 => Some(Syscall::timer_delete),
        227 => Some(Syscall::clock_settime),
        228 => Some(Syscall::clock_gettime),
        229 => Some(Syscall::clock_getres),
        230 => Some(Syscall::clock_nanosleep),
        231 => Some(Syscall::exit_group),
        232 => Some(Syscall::epoll_wait),
        233 => Some(Syscall::epoll_ctl),
        234 => Some(Syscall::tgkill),
        235 => Some(Syscall::utimes),
        236 => Some(Syscall::vserver),
        237 => Some(Syscall::mbind),
        238 => Some(Syscall::set_mempolicy),
        239 => Some(Syscall::get_mempolicy),
        240 => Some(Syscall::mq_open),
        241 => Some(Syscall::mq_unlink),
        242 => Some(Syscall::mq_timedsend),
        243 => Some(Syscall::mq_timedreceive),
        244 => Some(Syscall::mq_notify),
        245 => Some(Syscall::mq_getsetattr),
        246 => Some(Syscall::kexec_load),
        247 => Some(Syscall::waitid),
        248 => Some(Syscall::add_key),
        249 => Some(Syscall::request_key),
        250 => Some(Syscall::keyctl),
        251 => Some(Syscall::ioprio_set),
        252 => Some(Syscall::ioprio_get),
        253 => Some(Syscall::inotify_init),
        254 => Some(Syscall::inotify_add_watch),
        255 => Some(Syscall::inotify_rm_watch),
        256 => Some(Syscall::migrate_pages),
        257 => Some(Syscall::openat),
        258 => Some(Syscall::mkdirat),
        259 => Some(Syscall::mknodat),
        260 => Some(Syscall::fchownat),
        261 => Some(Syscall::futimesat),
        262 => Some(Syscall::newfstatat),
        263 => Some(Syscall::unlinkat),
        264 => Some(Syscall::renameat),
        265 => Some(Syscall::linkat),
        266 => Some(Syscall::symlinkat),
        267 => Some(Syscall::readlinkat),
        268 => Some(Syscall::fchmodat),
        269 => Some(Syscall::faccessat),
        270 => Some(Syscall::pselect6),
        271 => Some(Syscall::ppoll),
        272 => Some(Syscall::unshare),
        273 => Some(Syscall::set_robust_list),
        274 => Some(Syscall::get_robust_list),
        275 => Some(Syscall::splice),
        276 => Some(Syscall::tee),
        277 => Some(Syscall::sync_file_range),
        278 => Some(Syscall::vmsplice),
        279 => Some(Syscall::move_pages),
        280 => Some(Syscall::utimensat),
        281 => Some(Syscall::epoll_pwait),
        282 => Some(Syscall::signalfd),
        283 => Some(Syscall::timerfd_create),
        284 => Some(Syscall::eventfd),
        285 => Some(Syscall::fallocate),
        286 => Some(Syscall::timerfd_settime),
        287 => Some(Syscall::timerfd_gettime),
        288 => Some(Syscall::accept4),
        289 => Some(Syscall::signalfd4),
        290 => Some(Syscall::eventfd2),
        291 => Some(Syscall::epoll_create1),
        292 => Some(Syscall::dup3),
        293 => Some(Syscall::pipe2),
        294 => Some(Syscall::inotify_init1),
        295 => Some(Syscall::preadv),
        296 => Some(Syscall::pwritev),
        297 => Some(Syscall::rt_tgsigqueueinfo),
        298 => Some(Syscall::perf_event_open),
        299 => Some(Syscall::recvmmsg),
        300 => Some(Syscall::fanotify_init),
        301 => Some(Syscall::fanotify_mark),
        302 => Some(Syscall::prlimit64),
        303 => Some(Syscall::name_to_handle_at),
        304 => Some(Syscall::open_by_handle_at),
        305 => Some(Syscall::clock_adjtime),
        306 => Some(Syscall::syncfs),
        307 => Some(Syscall::sendmmsg),
        308 => Some(Syscall::setns),
        309 => Some(Syscall::getcpu),
        310 => Some(Syscall::process_vm_readv),
        311 => Some(Syscall::process_vm_writev),
        312 => Some(Syscall::kcmp),
        313 => Some(Syscall::finit_module),
        314 => Some(Syscall::sched_setattr),
        315 => Some(Syscall::sched_getattr),
        316 => Some(Syscall::renameat2),
        317 => Some(Syscall::seccomp),
        318 => Some(Syscall::getrandom),
        319 => Some(Syscall::memfd_create),
        320 => Some(Syscall::kexec_file_load),
        321 => Some(Syscall::bpf),
        322 => Some(Syscall::execveat),
        323 => Some(Syscall::userfaultfd),
        324 => Some(Syscall::membarrier),
        325 => Some(Syscall::mlock2),
        _ => None,
    }
}

pub fn from_str(x: &str) -> Option<Syscall> {
    match x {
        "read" => Some(Syscall::read),
        "write" => Some(Syscall::write),
        "open" => Some(Syscall::open),
        "close" => Some(Syscall::close),
        "stat" => Some(Syscall::stat),
        "fstat" => Some(Syscall::fstat),
        "lstat" => Some(Syscall::lstat),
        "poll" => Some(Syscall::poll),
        "lseek" => Some(Syscall::lseek),
        "mmap" => Some(Syscall::mmap),
        "mprotect" => Some(Syscall::mprotect),
        "munmap" => Some(Syscall::munmap),
        "brk" => Some(Syscall::brk),
        "rt_sigaction" => Some(Syscall::rt_sigaction),
        "rt_sigprocmask" => Some(Syscall::rt_sigprocmask),
        "rt_sigreturn" => Some(Syscall::rt_sigreturn),
        "ioctl" => Some(Syscall::ioctl),
        "pread64" => Some(Syscall::pread64),
        "pwrite64" => Some(Syscall::pwrite64),
        "readv" => Some(Syscall::readv),
        "writev" => Some(Syscall::writev),
        "access" => Some(Syscall::access),
        "pipe" => Some(Syscall::pipe),
        "select" => Some(Syscall::select),
        "sched_yield" => Some(Syscall::sched_yield),
        "mremap" => Some(Syscall::mremap),
        "msync" => Some(Syscall::msync),
        "mincore" => Some(Syscall::mincore),
        "madvise" => Some(Syscall::madvise),
        "shmget" => Some(Syscall::shmget),
        "shmat" => Some(Syscall::shmat),
        "shmctl" => Some(Syscall::shmctl),
        "dup" => Some(Syscall::dup),
        "dup2" => Some(Syscall::dup2),
        "pause" => Some(Syscall::pause),
        "nanosleep" => Some(Syscall::nanosleep),
        "getitimer" => Some(Syscall::getitimer),
        "alarm" => Some(Syscall::alarm),
        "setitimer" => Some(Syscall::setitimer),
        "getpid" => Some(Syscall::getpid),
        "sendfile" => Some(Syscall::sendfile),
        "socket" => Some(Syscall::socket),
        "connect" => Some(Syscall::connect),
        "accept" => Some(Syscall::accept),
        "sendto" => Some(Syscall::sendto),
        "recvfrom" => Some(Syscall::recvfrom),
        "sendmsg" => Some(Syscall::sendmsg),
        "recvmsg" => Some(Syscall::recvmsg),
        "shutdown" => Some(Syscall::shutdown),
        "bind" => Some(Syscall::bind),
        "listen" => Some(Syscall::listen),
        "getsockname" => Some(Syscall::getsockname),
        "getpeername" => Some(Syscall::getpeername),
        "socketpair" => Some(Syscall::socketpair),
        "setsockopt" => Some(Syscall::setsockopt),
        "getsockopt" => Some(Syscall::getsockopt),
        "clone" => Some(Syscall::clone),
        "fork" => Some(Syscall::fork),
        "vfork" => Some(Syscall::vfork),
        "execve" => Some(Syscall::execve),
        "exit" => Some(Syscall::exit),
        "wait4" => Some(Syscall::wait4),
        "kill" => Some(Syscall::kill),
        "uname" => Some(Syscall::uname),
        "semget" => Some(Syscall::semget),
        "semop" => Some(Syscall::semop),
        "semctl" => Some(Syscall::semctl),
        "shmdt" => Some(Syscall::shmdt),
        "msgget" => Some(Syscall::msgget),
        "msgsnd" => Some(Syscall::msgsnd),
        "msgrcv" => Some(Syscall::msgrcv),
        "msgctl" => Some(Syscall::msgctl),
        "fcntl" => Some(Syscall::fcntl),
        "flock" => Some(Syscall::flock),
        "fsync" => Some(Syscall::fsync),
        "fdatasync" => Some(Syscall::fdatasync),
        "truncate" => Some(Syscall::truncate),
        "ftruncate" => Some(Syscall::ftruncate),
        "getdents" => Some(Syscall::getdents),
        "getcwd" => Some(Syscall::getcwd),
        "chdir" => Some(Syscall::chdir),
        "fchdir" => Some(Syscall::fchdir),
        "rename" => Some(Syscall::rename),
        "mkdir" => Some(Syscall::mkdir),
        "rmdir" => Some(Syscall::rmdir),
        "creat" => Some(Syscall::creat),
        "link" => Some(Syscall::link),
        "unlink" => Some(Syscall::unlink),
        "symlink" => Some(Syscall::symlink),
        "readlink" => Some(Syscall::readlink),
        "chmod" => Some(Syscall::chmod),
        "fchmod" => Some(Syscall::fchmod),
        "chown" => Some(Syscall::chown),
        "fchown" => Some(Syscall::fchown),
        "lchown" => Some(Syscall::lchown),
        "umask" => Some(Syscall::umask),
        "gettimeofday" => Some(Syscall::gettimeofday),
        "getrlimit" => Some(Syscall::getrlimit),
        "getrusage" => Some(Syscall::getrusage),
        "sysinfo" => Some(Syscall::sysinfo),
        "times" => Some(Syscall::times),
        "ptrace" => Some(Syscall::ptrace),
        "getuid" => Some(Syscall::getuid),
        "syslog" => Some(Syscall::syslog),
        "getgid" => Some(Syscall::getgid),
        "setuid" => Some(Syscall::setuid),
        "setgid" => Some(Syscall::setgid),
        "geteuid" => Some(Syscall::geteuid),
        "getegid" => Some(Syscall::getegid),
        "setpgid" => Some(Syscall::setpgid),
        "getppid" => Some(Syscall::getppid),
        "getpgrp" => Some(Syscall::getpgrp),
        "setsid" => Some(Syscall::setsid),
        "setreuid" => Some(Syscall::setreuid),
        "setregid" => Some(Syscall::setregid),
        "getgroups" => Some(Syscall::getgroups),
        "setgroups" => Some(Syscall::setgroups),
        "setresuid" => Some(Syscall::setresuid),
        "getresuid" => Some(Syscall::getresuid),
        "setresgid" => Some(Syscall::setresgid),
        "getresgid" => Some(Syscall::getresgid),
        "getpgid" => Some(Syscall::getpgid),
        "setfsuid" => Some(Syscall::setfsuid),
        "setfsgid" => Some(Syscall::setfsgid),
        "getsid" => Some(Syscall::getsid),
        "capget" => Some(Syscall::capget),
        "capset" => Some(Syscall::capset),
        "rt_sigpending" => Some(Syscall::rt_sigpending),
        "rt_sigtimedwait" => Some(Syscall::rt_sigtimedwait),
        "rt_sigqueueinfo" => Some(Syscall::rt_sigqueueinfo),
        "rt_sigsuspend" => Some(Syscall::rt_sigsuspend),
        "sigaltstack" => Some(Syscall::sigaltstack),
        "utime" => Some(Syscall::utime),
        "mknod" => Some(Syscall::mknod),
        "uselib" => Some(Syscall::uselib),
        "personality" => Some(Syscall::personality),
        "ustat" => Some(Syscall::ustat),
        "statfs" => Some(Syscall::statfs),
        "fstatfs" => Some(Syscall::fstatfs),
        "sysfs" => Some(Syscall::sysfs),
        "getpriority" => Some(Syscall::getpriority),
        "setpriority" => Some(Syscall::setpriority),
        "sched_setparam" => Some(Syscall::sched_setparam),
        "sched_getparam" => Some(Syscall::sched_getparam),
        "sched_setscheduler" => Some(Syscall::sched_setscheduler),
        "sched_getscheduler" => Some(Syscall::sched_getscheduler),
        "sched_get_priority_max" => Some(Syscall::sched_get_priority_max),
        "sched_get_priority_min" => Some(Syscall::sched_get_priority_min),
        "sched_rr_get_interval" => Some(Syscall::sched_rr_get_interval),
        "mlock" => Some(Syscall::mlock),
        "munlock" => Some(Syscall::munlock),
        "mlockall" => Some(Syscall::mlockall),
        "munlockall" => Some(Syscall::munlockall),
        "vhangup" => Some(Syscall::vhangup),
        "modify_ldt" => Some(Syscall::modify_ldt),
        "pivot_root" => Some(Syscall::pivot_root),
        "_sysctl" => Some(Syscall::_sysctl),
        "prctl" => Some(Syscall::prctl),
        "arch_prctl" => Some(Syscall::arch_prctl),
        "adjtimex" => Some(Syscall::adjtimex),
        "setrlimit" => Some(Syscall::setrlimit),
        "chroot" => Some(Syscall::chroot),
        "sync" => Some(Syscall::sync),
        "acct" => Some(Syscall::acct),
        "settimeofday" => Some(Syscall::settimeofday),
        "mount" => Some(Syscall::mount),
        "umount2" => Some(Syscall::umount2),
        "swapon" => Some(Syscall::swapon),
        "swapoff" => Some(Syscall::swapoff),
        "reboot" => Some(Syscall::reboot),
        "sethostname" => Some(Syscall::sethostname),
        "setdomainname" => Some(Syscall::setdomainname),
        "iopl" => Some(Syscall::iopl),
        "ioperm" => Some(Syscall::ioperm),
        "create_module" => Some(Syscall::create_module),
        "init_module" => Some(Syscall::init_module),
        "delete_module" => Some(Syscall::delete_module),
        "get_kernel_syms" => Some(Syscall::get_kernel_syms),
        "query_module" => Some(Syscall::query_module),
        "quotactl" => Some(Syscall::quotactl),
        "nfsservctl" => Some(Syscall::nfsservctl),
        "getpmsg" => Some(Syscall::getpmsg),
        "putpmsg" => Some(Syscall::putpmsg),
        "afs_syscall" => Some(Syscall::afs_syscall),
        "tuxcall" => Some(Syscall::tuxcall),
        "security" => Some(Syscall::security),
        "gettid" => Some(Syscall::gettid),
        "readahead" => Some(Syscall::readahead),
        "setxattr" => Some(Syscall::setxattr),
        "lsetxattr" => Some(Syscall::lsetxattr),
        "fsetxattr" => Some(Syscall::fsetxattr),
        "getxattr" => Some(Syscall::getxattr),
        "lgetxattr" => Some(Syscall::lgetxattr),
        "fgetxattr" => Some(Syscall::fgetxattr),
        "listxattr" => Some(Syscall::listxattr),
        "llistxattr" => Some(Syscall::llistxattr),
        "flistxattr" => Some(Syscall::flistxattr),
        "removexattr" => Some(Syscall::removexattr),
        "lremovexattr" => Some(Syscall::lremovexattr),
        "fremovexattr" => Some(Syscall::fremovexattr),
        "tkill" => Some(Syscall::tkill),
        "time" => Some(Syscall::time),
        "futex" => Some(Syscall::futex),
        "sched_setaffinity" => Some(Syscall::sched_setaffinity),
        "sched_getaffinity" => Some(Syscall::sched_getaffinity),
        "set_thread_area" => Some(Syscall::set_thread_area),
        "io_setup" => Some(Syscall::io_setup),
        "io_destroy" => Some(Syscall::io_destroy),
        "io_getevents" => Some(Syscall::io_getevents),
        "io_submit" => Some(Syscall::io_submit),
        "io_cancel" => Some(Syscall::io_cancel),
        "get_thread_area" => Some(Syscall::get_thread_area),
        "lookup_dcookie" => Some(Syscall::lookup_dcookie),
        "epoll_create" => Some(Syscall::epoll_create),
        "epoll_ctl_old" => Some(Syscall::epoll_ctl_old),
        "epoll_wait_old" => Some(Syscall::epoll_wait_old),
        "remap_file_pages" => Some(Syscall::remap_file_pages),
        "getdents64" => Some(Syscall::getdents64),
        "set_tid_address" => Some(Syscall::set_tid_address),
        "restart_syscall" => Some(Syscall::restart_syscall),
        "semtimedop" => Some(Syscall::semtimedop),
        "fadvise64" => Some(Syscall::fadvise64),
        "timer_create" => Some(Syscall::timer_create),
        "timer_settime" => Some(Syscall::timer_settime),
        "timer_gettime" => Some(Syscall::timer_gettime),
        "timer_getoverrun" => Some(Syscall::timer_getoverrun),
        "timer_delete" => Some(Syscall::timer_delete),
        "clock_settime" => Some(Syscall::clock_settime),
        "clock_gettime" => Some(Syscall::clock_gettime),
        "clock_getres" => Some(Syscall::clock_getres),
        "clock_nanosleep" => Some(Syscall::clock_nanosleep),
        "exit_group" => Some(Syscall::exit_group),
        "epoll_wait" => Some(Syscall::epoll_wait),
        "epoll_ctl" => Some(Syscall::epoll_ctl),
        "tgkill" => Some(Syscall::tgkill),
        "utimes" => Some(Syscall::utimes),
        "vserver" => Some(Syscall::vserver),
        "mbind" => Some(Syscall::mbind),
        "set_mempolicy" => Some(Syscall::set_mempolicy),
        "get_mempolicy" => Some(Syscall::get_mempolicy),
        "mq_open" => Some(Syscall::mq_open),
        "mq_unlink" => Some(Syscall::mq_unlink),
        "mq_timedsend" => Some(Syscall::mq_timedsend),
        "mq_timedreceive" => Some(Syscall::mq_timedreceive),
        "mq_notify" => Some(Syscall::mq_notify),
        "mq_getsetattr" => Some(Syscall::mq_getsetattr),
        "kexec_load" => Some(Syscall::kexec_load),
        "waitid" => Some(Syscall::waitid),
        "add_key" => Some(Syscall::add_key),
        "request_key" => Some(Syscall::request_key),
        "keyctl" => Some(Syscall::keyctl),
        "ioprio_set" => Some(Syscall::ioprio_set),
        "ioprio_get" => Some(Syscall::ioprio_get),
        "inotify_init" => Some(Syscall::inotify_init),
        "inotify_add_watch" => Some(Syscall::inotify_add_watch),
        "inotify_rm_watch" => Some(Syscall::inotify_rm_watch),
        "migrate_pages" => Some(Syscall::migrate_pages),
        "openat" => Some(Syscall::openat),
        "mkdirat" => Some(Syscall::mkdirat),
        "mknodat" => Some(Syscall::mknodat),
        "fchownat" => Some(Syscall::fchownat),
        "futimesat" => Some(Syscall::futimesat),
        "newfstatat" => Some(Syscall::newfstatat),
        "unlinkat" => Some(Syscall::unlinkat),
        "renameat" => Some(Syscall::renameat),
        "linkat" => Some(Syscall::linkat),
        "symlinkat" => Some(Syscall::symlinkat),
        "readlinkat" => Some(Syscall::readlinkat),
        "fchmodat" => Some(Syscall::fchmodat),
        "faccessat" => Some(Syscall::faccessat),
        "pselect6" => Some(Syscall::pselect6),
        "ppoll" => Some(Syscall::ppoll),
        "unshare" => Some(Syscall::unshare),
        "set_robust_list" => Some(Syscall::set_robust_list),
        "get_robust_list" => Some(Syscall::get_robust_list),
        "splice" => Some(Syscall::splice),
        "tee" => Some(Syscall::tee),
        "sync_file_range" => Some(Syscall::sync_file_range),
        "vmsplice" => Some(Syscall::vmsplice),
        "move_pages" => Some(Syscall::move_pages),
        "utimensat" => Some(Syscall::utimensat),
        "epoll_pwait" => Some(Syscall::epoll_pwait),
        "signalfd" => Some(Syscall::signalfd),
        "timerfd_create" => Some(Syscall::timerfd_create),
        "eventfd" => Some(Syscall::eventfd),
        "fallocate" => Some(Syscall::fallocate),
        "timerfd_settime" => Some(Syscall::timerfd_settime),
        "timerfd_gettime" => Some(Syscall::timerfd_gettime),
        "accept4" => Some(Syscall::accept4),
        "signalfd4" => Some(Syscall::signalfd4),
        "eventfd2" => Some(Syscall::eventfd2),
        "epoll_create1" => Some(Syscall::epoll_create1),
        "dup3" => Some(Syscall::dup3),
        "pipe2" => Some(Syscall::pipe2),
        "inotify_init1" => Some(Syscall::inotify_init1),
        "preadv" => Some(Syscall::preadv),
        "pwritev" => Some(Syscall::pwritev),
        "rt_tgsigqueueinfo" => Some(Syscall::rt_tgsigqueueinfo),
        "perf_event_open" => Some(Syscall::perf_event_open),
        "recvmmsg" => Some(Syscall::recvmmsg),
        "fanotify_init" => Some(Syscall::fanotify_init),
        "fanotify_mark" => Some(Syscall::fanotify_mark),
        "prlimit64" => Some(Syscall::prlimit64),
        "name_to_handle_at" => Some(Syscall::name_to_handle_at),
        "open_by_handle_at" => Some(Syscall::open_by_handle_at),
        "clock_adjtime" => Some(Syscall::clock_adjtime),
        "syncfs" => Some(Syscall::syncfs),
        "sendmmsg" => Some(Syscall::sendmmsg),
        "setns" => Some(Syscall::setns),
        "getcpu" => Some(Syscall::getcpu),
        "process_vm_readv" => Some(Syscall::process_vm_readv),
        "process_vm_writev" => Some(Syscall::process_vm_writev),
        "kcmp" => Some(Syscall::kcmp),
        "finit_module" => Some(Syscall::finit_module),
        "sched_setattr" => Some(Syscall::sched_setattr),
        "sched_getattr" => Some(Syscall::sched_getattr),
        "renameat2" => Some(Syscall::renameat2),
        "seccomp" => Some(Syscall::seccomp),
        "getrandom" => Some(Syscall::getrandom),
        "memfd_create" => Some(Syscall::memfd_create),
        "kexec_file_load" => Some(Syscall::kexec_file_load),
        "bpf" => Some(Syscall::bpf),
        "execveat" => Some(Syscall::execveat),
        "userfaultfd" => Some(Syscall::userfaultfd),
        "membarrier" => Some(Syscall::membarrier),
        "mlock2" => Some(Syscall::mlock2),
        _ => None,
    }
}

pub const LIST: &'static [Syscall] = &[
    Syscall::read,
    Syscall::write,
    Syscall::open,
    Syscall::close,
    Syscall::stat,
    Syscall::fstat,
    Syscall::lstat,
    Syscall::poll,
    Syscall::lseek,
    Syscall::mmap,
    Syscall::mprotect,
    Syscall::munmap,
    Syscall::brk,
    Syscall::rt_sigaction,
    Syscall::rt_sigprocmask,
    Syscall::rt_sigreturn,
    Syscall::ioctl,
    Syscall::pread64,
    Syscall::pwrite64,
    Syscall::readv,
    Syscall::writev,
    Syscall::access,
    Syscall::pipe,
    Syscall::select,
    Syscall::sched_yield,
    Syscall::mremap,
    Syscall::msync,
    Syscall::mincore,
    Syscall::madvise,
    Syscall::shmget,
    Syscall::shmat,
    Syscall::shmctl,
    Syscall::dup,
    Syscall::dup2,
    Syscall::pause,
    Syscall::nanosleep,
    Syscall::getitimer,
    Syscall::alarm,
    Syscall::setitimer,
    Syscall::getpid,
    Syscall::sendfile,
    Syscall::socket,
    Syscall::connect,
    Syscall::accept,
    Syscall::sendto,
    Syscall::recvfrom,
    Syscall::sendmsg,
    Syscall::recvmsg,
    Syscall::shutdown,
    Syscall::bind,
    Syscall::listen,
    Syscall::getsockname,
    Syscall::getpeername,
    Syscall::socketpair,
    Syscall::setsockopt,
    Syscall::getsockopt,
    Syscall::clone,
    Syscall::fork,
    Syscall::vfork,
    Syscall::execve,
    Syscall::exit,
    Syscall::wait4,
    Syscall::kill,
    Syscall::uname,
    Syscall::semget,
    Syscall::semop,
    Syscall::semctl,
    Syscall::shmdt,
    Syscall::msgget,
    Syscall::msgsnd,
    Syscall::msgrcv,
    Syscall::msgctl,
    Syscall::fcntl,
    Syscall::flock,
    Syscall::fsync,
    Syscall::fdatasync,
    Syscall::truncate,
    Syscall::ftruncate,
    Syscall::getdents,
    Syscall::getcwd,
    Syscall::chdir,
    Syscall::fchdir,
    Syscall::rename,
    Syscall::mkdir,
    Syscall::rmdir,
    Syscall::creat,
    Syscall::link,
    Syscall::unlink,
    Syscall::symlink,
    Syscall::readlink,
    Syscall::chmod,
    Syscall::fchmod,
    Syscall::chown,
    Syscall::fchown,
    Syscall::lchown,
    Syscall::umask,
    Syscall::gettimeofday,
    Syscall::getrlimit,
    Syscall::getrusage,
    Syscall::sysinfo,
    Syscall::times,
    Syscall::ptrace,
    Syscall::getuid,
    Syscall::syslog,
    Syscall::getgid,
    Syscall::setuid,
    Syscall::setgid,
    Syscall::geteuid,
    Syscall::getegid,
    Syscall::setpgid,
    Syscall::getppid,
    Syscall::getpgrp,
    Syscall::setsid,
    Syscall::setreuid,
    Syscall::setregid,
    Syscall::getgroups,
    Syscall::setgroups,
    Syscall::setresuid,
    Syscall::getresuid,
    Syscall::setresgid,
    Syscall::getresgid,
    Syscall::getpgid,
    Syscall::setfsuid,
    Syscall::setfsgid,
    Syscall::getsid,
    Syscall::capget,
    Syscall::capset,
    Syscall::rt_sigpending,
    Syscall::rt_sigtimedwait,
    Syscall::rt_sigqueueinfo,
    Syscall::rt_sigsuspend,
    Syscall::sigaltstack,
    Syscall::utime,
    Syscall::mknod,
    Syscall::uselib,
    Syscall::personality,
    Syscall::ustat,
    Syscall::statfs,
    Syscall::fstatfs,
    Syscall::sysfs,
    Syscall::getpriority,
    Syscall::setpriority,
    Syscall::sched_setparam,
    Syscall::sched_getparam,
    Syscall::sched_setscheduler,
    Syscall::sched_getscheduler,
    Syscall::sched_get_priority_max,
    Syscall::sched_get_priority_min,
    Syscall::sched_rr_get_interval,
    Syscall::mlock,
    Syscall::munlock,
    Syscall::mlockall,
    Syscall::munlockall,
    Syscall::vhangup,
    Syscall::modify_ldt,
    Syscall::pivot_root,
    Syscall::_sysctl,
    Syscall::prctl,
    Syscall::arch_prctl,
    Syscall::adjtimex,
    Syscall::setrlimit,
    Syscall::chroot,
    Syscall::sync,
    Syscall::acct,
    Syscall::settimeofday,
    Syscall::mount,
    Syscall::umount2,
    Syscall::swapon,
    Syscall::swapoff,
    Syscall::reboot,
    Syscall::sethostname,
    Syscall::setdomainname,
    Syscall::iopl,
    Syscall::ioperm,
    Syscall::create_module,
    Syscall::init_module,
    Syscall::delete_module,
    Syscall::get_kernel_syms,
    Syscall::query_module,
    Syscall::quotactl,
    Syscall::nfsservctl,
    Syscall::getpmsg,
    Syscall::putpmsg,
    Syscall::afs_syscall,
    Syscall::tuxcall,
    Syscall::security,
    Syscall::gettid,
    Syscall::readahead,
    Syscall::setxattr,
    Syscall::lsetxattr,
    Syscall::fsetxattr,
    Syscall::getxattr,
    Syscall::lgetxattr,
    Syscall::fgetxattr,
    Syscall::listxattr,
    Syscall::llistxattr,
    Syscall::flistxattr,
    Syscall::removexattr,
    Syscall::lremovexattr,
    Syscall::fremovexattr,
    Syscall::tkill,
    Syscall::time,
    Syscall::futex,
    Syscall::sched_setaffinity,
    Syscall::sched_getaffinity,
    Syscall::set_thread_area,
    Syscall::io_setup,
    Syscall::io_destroy,
    Syscall::io_getevents,
    Syscall::io_submit,
    Syscall::io_cancel,
    Syscall::get_thread_area,
    Syscall::lookup_dcookie,
    Syscall::epoll_create,
    Syscall::epoll_ctl_old,
    Syscall::epoll_wait_old,
    Syscall::remap_file_pages,
    Syscall::getdents64,
    Syscall::set_tid_address,
    Syscall::restart_syscall,
    Syscall::semtimedop,
    Syscall::fadvise64,
    Syscall::timer_create,
    Syscall::timer_settime,
    Syscall::timer_gettime,
    Syscall::timer_getoverrun,
    Syscall::timer_delete,
    Syscall::clock_settime,
    Syscall::clock_gettime,
    Syscall::clock_getres,
    Syscall::clock_nanosleep,
    Syscall::exit_group,
    Syscall::epoll_wait,
    Syscall::epoll_ctl,
    Syscall::tgkill,
    Syscall::utimes,
    Syscall::vserver,
    Syscall::mbind,
    Syscall::set_mempolicy,
    Syscall::get_mempolicy,
    Syscall::mq_open,
    Syscall::mq_unlink,
    Syscall::mq_timedsend,
    Syscall::mq_timedreceive,
    Syscall::mq_notify,
    Syscall::mq_getsetattr,
    Syscall::kexec_load,
    Syscall::waitid,
    Syscall::add_key,
    Syscall::request_key,
    Syscall::keyctl,
    Syscall::ioprio_set,
    Syscall::ioprio_get,
    Syscall::inotify_init,
    Syscall::inotify_add_watch,
    Syscall::inotify_rm_watch,
    Syscall::migrate_pages,
    Syscall::openat,
    Syscall::mkdirat,
    Syscall::mknodat,
    Syscall::fchownat,
    Syscall::futimesat,
    Syscall::newfstatat,
    Syscall::unlinkat,
    Syscall::renameat,
    Syscall::linkat,
    Syscall::symlinkat,
    Syscall::readlinkat,
    Syscall::fchmodat,
    Syscall::faccessat,
    Syscall::pselect6,
    Syscall::ppoll,
    Syscall::unshare,
    Syscall::set_robust_list,
    Syscall::get_robust_list,
    Syscall::splice,
    Syscall::tee,
    Syscall::sync_file_range,
    Syscall::vmsplice,
    Syscall::move_pages,
    Syscall::utimensat,
    Syscall::epoll_pwait,
    Syscall::signalfd,
    Syscall::timerfd_create,
    Syscall::eventfd,
    Syscall::fallocate,
    Syscall::timerfd_settime,
    Syscall::timerfd_gettime,
    Syscall::accept4,
    Syscall::signalfd4,
    Syscall::eventfd2,
    Syscall::epoll_create1,
    Syscall::dup3,
    Syscall::pipe2,
    Syscall::inotify_init1,
    Syscall::preadv,
    Syscall::pwritev,
    Syscall::rt_tgsigqueueinfo,
    Syscall::perf_event_open,
    Syscall::recvmmsg,
    Syscall::fanotify_init,
    Syscall::fanotify_mark,
    Syscall::prlimit64,
    Syscall::name_to_handle_at,
    Syscall::open_by_handle_at,
    Syscall::clock_adjtime,
    Syscall::syncfs,
    Syscall::sendmmsg,
    Syscall::setns,
    Syscall::getcpu,
    Syscall::process_vm_readv,
    Syscall::process_vm_writev,
    Syscall::kcmp,
    Syscall::finit_module,
    Syscall::sched_setattr,
    Syscall::sched_getattr,
    Syscall::renameat2,
    Syscall::seccomp,
    Syscall::getrandom,
    Syscall::memfd_create,
    Syscall::kexec_file_load,
    Syscall::bpf,
    Syscall::execveat,
    Syscall::userfaultfd,
    Syscall::membarrier,
    Syscall::mlock2,
];

impl Serialize for Syscall {
    fn serialize<S: Serializer>(&self, s: &mut S) -> Result<(), S::Error> {
        s.serialize_str(match *self {
            Syscall::read => "read",
            Syscall::write => "write",
            Syscall::open => "open",
            Syscall::close => "close",
            Syscall::stat => "stat",
            Syscall::fstat => "fstat",
            Syscall::lstat => "lstat",
            Syscall::poll => "poll",
            Syscall::lseek => "lseek",
            Syscall::mmap => "mmap",
            Syscall::mprotect => "mprotect",
            Syscall::munmap => "munmap",
            Syscall::brk => "brk",
            Syscall::rt_sigaction => "rt_sigaction",
            Syscall::rt_sigprocmask => "rt_sigprocmask",
            Syscall::rt_sigreturn => "rt_sigreturn",
            Syscall::ioctl => "ioctl",
            Syscall::pread64 => "pread64",
            Syscall::pwrite64 => "pwrite64",
            Syscall::readv => "readv",
            Syscall::writev => "writev",
            Syscall::access => "access",
            Syscall::pipe => "pipe",
            Syscall::select => "select",
            Syscall::sched_yield => "sched_yield",
            Syscall::mremap => "mremap",
            Syscall::msync => "msync",
            Syscall::mincore => "mincore",
            Syscall::madvise => "madvise",
            Syscall::shmget => "shmget",
            Syscall::shmat => "shmat",
            Syscall::shmctl => "shmctl",
            Syscall::dup => "dup",
            Syscall::dup2 => "dup2",
            Syscall::pause => "pause",
            Syscall::nanosleep => "nanosleep",
            Syscall::getitimer => "getitimer",
            Syscall::alarm => "alarm",
            Syscall::setitimer => "setitimer",
            Syscall::getpid => "getpid",
            Syscall::sendfile => "sendfile",
            Syscall::socket => "socket",
            Syscall::connect => "connect",
            Syscall::accept => "accept",
            Syscall::sendto => "sendto",
            Syscall::recvfrom => "recvfrom",
            Syscall::sendmsg => "sendmsg",
            Syscall::recvmsg => "recvmsg",
            Syscall::shutdown => "shutdown",
            Syscall::bind => "bind",
            Syscall::listen => "listen",
            Syscall::getsockname => "getsockname",
            Syscall::getpeername => "getpeername",
            Syscall::socketpair => "socketpair",
            Syscall::setsockopt => "setsockopt",
            Syscall::getsockopt => "getsockopt",
            Syscall::clone => "clone",
            Syscall::fork => "fork",
            Syscall::vfork => "vfork",
            Syscall::execve => "execve",
            Syscall::exit => "exit",
            Syscall::wait4 => "wait4",
            Syscall::kill => "kill",
            Syscall::uname => "uname",
            Syscall::semget => "semget",
            Syscall::semop => "semop",
            Syscall::semctl => "semctl",
            Syscall::shmdt => "shmdt",
            Syscall::msgget => "msgget",
            Syscall::msgsnd => "msgsnd",
            Syscall::msgrcv => "msgrcv",
            Syscall::msgctl => "msgctl",
            Syscall::fcntl => "fcntl",
            Syscall::flock => "flock",
            Syscall::fsync => "fsync",
            Syscall::fdatasync => "fdatasync",
            Syscall::truncate => "truncate",
            Syscall::ftruncate => "ftruncate",
            Syscall::getdents => "getdents",
            Syscall::getcwd => "getcwd",
            Syscall::chdir => "chdir",
            Syscall::fchdir => "fchdir",
            Syscall::rename => "rename",
            Syscall::mkdir => "mkdir",
            Syscall::rmdir => "rmdir",
            Syscall::creat => "creat",
            Syscall::link => "link",
            Syscall::unlink => "unlink",
            Syscall::symlink => "symlink",
            Syscall::readlink => "readlink",
            Syscall::chmod => "chmod",
            Syscall::fchmod => "fchmod",
            Syscall::chown => "chown",
            Syscall::fchown => "fchown",
            Syscall::lchown => "lchown",
            Syscall::umask => "umask",
            Syscall::gettimeofday => "gettimeofday",
            Syscall::getrlimit => "getrlimit",
            Syscall::getrusage => "getrusage",
            Syscall::sysinfo => "sysinfo",
            Syscall::times => "times",
            Syscall::ptrace => "ptrace",
            Syscall::getuid => "getuid",
            Syscall::syslog => "syslog",
            Syscall::getgid => "getgid",
            Syscall::setuid => "setuid",
            Syscall::setgid => "setgid",
            Syscall::geteuid => "geteuid",
            Syscall::getegid => "getegid",
            Syscall::setpgid => "setpgid",
            Syscall::getppid => "getppid",
            Syscall::getpgrp => "getpgrp",
            Syscall::setsid => "setsid",
            Syscall::setreuid => "setreuid",
            Syscall::setregid => "setregid",
            Syscall::getgroups => "getgroups",
            Syscall::setgroups => "setgroups",
            Syscall::setresuid => "setresuid",
            Syscall::getresuid => "getresuid",
            Syscall::setresgid => "setresgid",
            Syscall::getresgid => "getresgid",
            Syscall::getpgid => "getpgid",
            Syscall::setfsuid => "setfsuid",
            Syscall::setfsgid => "setfsgid",
            Syscall::getsid => "getsid",
            Syscall::capget => "capget",
            Syscall::capset => "capset",
            Syscall::rt_sigpending => "rt_sigpending",
            Syscall::rt_sigtimedwait => "rt_sigtimedwait",
            Syscall::rt_sigqueueinfo => "rt_sigqueueinfo",
            Syscall::rt_sigsuspend => "rt_sigsuspend",
            Syscall::sigaltstack => "sigaltstack",
            Syscall::utime => "utime",
            Syscall::mknod => "mknod",
            Syscall::uselib => "uselib",
            Syscall::personality => "personality",
            Syscall::ustat => "ustat",
            Syscall::statfs => "statfs",
            Syscall::fstatfs => "fstatfs",
            Syscall::sysfs => "sysfs",
            Syscall::getpriority => "getpriority",
            Syscall::setpriority => "setpriority",
            Syscall::sched_setparam => "sched_setparam",
            Syscall::sched_getparam => "sched_getparam",
            Syscall::sched_setscheduler => "sched_setscheduler",
            Syscall::sched_getscheduler => "sched_getscheduler",
            Syscall::sched_get_priority_max => "sched_get_priority_max",
            Syscall::sched_get_priority_min => "sched_get_priority_min",
            Syscall::sched_rr_get_interval => "sched_rr_get_interval",
            Syscall::mlock => "mlock",
            Syscall::munlock => "munlock",
            Syscall::mlockall => "mlockall",
            Syscall::munlockall => "munlockall",
            Syscall::vhangup => "vhangup",
            Syscall::modify_ldt => "modify_ldt",
            Syscall::pivot_root => "pivot_root",
            Syscall::_sysctl => "_sysctl",
            Syscall::prctl => "prctl",
            Syscall::arch_prctl => "arch_prctl",
            Syscall::adjtimex => "adjtimex",
            Syscall::setrlimit => "setrlimit",
            Syscall::chroot => "chroot",
            Syscall::sync => "sync",
            Syscall::acct => "acct",
            Syscall::settimeofday => "settimeofday",
            Syscall::mount => "mount",
            Syscall::umount2 => "umount2",
            Syscall::swapon => "swapon",
            Syscall::swapoff => "swapoff",
            Syscall::reboot => "reboot",
            Syscall::sethostname => "sethostname",
            Syscall::setdomainname => "setdomainname",
            Syscall::iopl => "iopl",
            Syscall::ioperm => "ioperm",
            Syscall::create_module => "create_module",
            Syscall::init_module => "init_module",
            Syscall::delete_module => "delete_module",
            Syscall::get_kernel_syms => "get_kernel_syms",
            Syscall::query_module => "query_module",
            Syscall::quotactl => "quotactl",
            Syscall::nfsservctl => "nfsservctl",
            Syscall::getpmsg => "getpmsg",
            Syscall::putpmsg => "putpmsg",
            Syscall::afs_syscall => "afs_syscall",
            Syscall::tuxcall => "tuxcall",
            Syscall::security => "security",
            Syscall::gettid => "gettid",
            Syscall::readahead => "readahead",
            Syscall::setxattr => "setxattr",
            Syscall::lsetxattr => "lsetxattr",
            Syscall::fsetxattr => "fsetxattr",
            Syscall::getxattr => "getxattr",
            Syscall::lgetxattr => "lgetxattr",
            Syscall::fgetxattr => "fgetxattr",
            Syscall::listxattr => "listxattr",
            Syscall::llistxattr => "llistxattr",
            Syscall::flistxattr => "flistxattr",
            Syscall::removexattr => "removexattr",
            Syscall::lremovexattr => "lremovexattr",
            Syscall::fremovexattr => "fremovexattr",
            Syscall::tkill => "tkill",
            Syscall::time => "time",
            Syscall::futex => "futex",
            Syscall::sched_setaffinity => "sched_setaffinity",
            Syscall::sched_getaffinity => "sched_getaffinity",
            Syscall::set_thread_area => "set_thread_area",
            Syscall::io_setup => "io_setup",
            Syscall::io_destroy => "io_destroy",
            Syscall::io_getevents => "io_getevents",
            Syscall::io_submit => "io_submit",
            Syscall::io_cancel => "io_cancel",
            Syscall::get_thread_area => "get_thread_area",
            Syscall::lookup_dcookie => "lookup_dcookie",
            Syscall::epoll_create => "epoll_create",
            Syscall::epoll_ctl_old => "epoll_ctl_old",
            Syscall::epoll_wait_old => "epoll_wait_old",
            Syscall::remap_file_pages => "remap_file_pages",
            Syscall::getdents64 => "getdents64",
            Syscall::set_tid_address => "set_tid_address",
            Syscall::restart_syscall => "restart_syscall",
            Syscall::semtimedop => "semtimedop",
            Syscall::fadvise64 => "fadvise64",
            Syscall::timer_create => "timer_create",
            Syscall::timer_settime => "timer_settime",
            Syscall::timer_gettime => "timer_gettime",
            Syscall::timer_getoverrun => "timer_getoverrun",
            Syscall::timer_delete => "timer_delete",
            Syscall::clock_settime => "clock_settime",
            Syscall::clock_gettime => "clock_gettime",
            Syscall::clock_getres => "clock_getres",
            Syscall::clock_nanosleep => "clock_nanosleep",
            Syscall::exit_group => "exit_group",
            Syscall::epoll_wait => "epoll_wait",
            Syscall::epoll_ctl => "epoll_ctl",
            Syscall::tgkill => "tgkill",
            Syscall::utimes => "utimes",
            Syscall::vserver => "vserver",
            Syscall::mbind => "mbind",
            Syscall::set_mempolicy => "set_mempolicy",
            Syscall::get_mempolicy => "get_mempolicy",
            Syscall::mq_open => "mq_open",
            Syscall::mq_unlink => "mq_unlink",
            Syscall::mq_timedsend => "mq_timedsend",
            Syscall::mq_timedreceive => "mq_timedreceive",
            Syscall::mq_notify => "mq_notify",
            Syscall::mq_getsetattr => "mq_getsetattr",
            Syscall::kexec_load => "kexec_load",
            Syscall::waitid => "waitid",
            Syscall::add_key => "add_key",
            Syscall::request_key => "request_key",
            Syscall::keyctl => "keyctl",
            Syscall::ioprio_set => "ioprio_set",
            Syscall::ioprio_get => "ioprio_get",
            Syscall::inotify_init => "inotify_init",
            Syscall::inotify_add_watch => "inotify_add_watch",
            Syscall::inotify_rm_watch => "inotify_rm_watch",
            Syscall::migrate_pages => "migrate_pages",
            Syscall::openat => "openat",
            Syscall::mkdirat => "mkdirat",
            Syscall::mknodat => "mknodat",
            Syscall::fchownat => "fchownat",
            Syscall::futimesat => "futimesat",
            Syscall::newfstatat => "newfstatat",
            Syscall::unlinkat => "unlinkat",
            Syscall::renameat => "renameat",
            Syscall::linkat => "linkat",
            Syscall::symlinkat => "symlinkat",
            Syscall::readlinkat => "readlinkat",
            Syscall::fchmodat => "fchmodat",
            Syscall::faccessat => "faccessat",
            Syscall::pselect6 => "pselect6",
            Syscall::ppoll => "ppoll",
            Syscall::unshare => "unshare",
            Syscall::set_robust_list => "set_robust_list",
            Syscall::get_robust_list => "get_robust_list",
            Syscall::splice => "splice",
            Syscall::tee => "tee",
            Syscall::sync_file_range => "sync_file_range",
            Syscall::vmsplice => "vmsplice",
            Syscall::move_pages => "move_pages",
            Syscall::utimensat => "utimensat",
            Syscall::epoll_pwait => "epoll_pwait",
            Syscall::signalfd => "signalfd",
            Syscall::timerfd_create => "timerfd_create",
            Syscall::eventfd => "eventfd",
            Syscall::fallocate => "fallocate",
            Syscall::timerfd_settime => "timerfd_settime",
            Syscall::timerfd_gettime => "timerfd_gettime",
            Syscall::accept4 => "accept4",
            Syscall::signalfd4 => "signalfd4",
            Syscall::eventfd2 => "eventfd2",
            Syscall::epoll_create1 => "epoll_create1",
            Syscall::dup3 => "dup3",
            Syscall::pipe2 => "pipe2",
            Syscall::inotify_init1 => "inotify_init1",
            Syscall::preadv => "preadv",
            Syscall::pwritev => "pwritev",
            Syscall::rt_tgsigqueueinfo => "rt_tgsigqueueinfo",
            Syscall::perf_event_open => "perf_event_open",
            Syscall::recvmmsg => "recvmmsg",
            Syscall::fanotify_init => "fanotify_init",
            Syscall::fanotify_mark => "fanotify_mark",
            Syscall::prlimit64 => "prlimit64",
            Syscall::name_to_handle_at => "name_to_handle_at",
            Syscall::open_by_handle_at => "open_by_handle_at",
            Syscall::clock_adjtime => "clock_adjtime",
            Syscall::syncfs => "syncfs",
            Syscall::sendmmsg => "sendmmsg",
            Syscall::setns => "setns",
            Syscall::getcpu => "getcpu",
            Syscall::process_vm_readv => "process_vm_readv",
            Syscall::process_vm_writev => "process_vm_writev",
            Syscall::kcmp => "kcmp",
            Syscall::finit_module => "finit_module",
            Syscall::sched_setattr => "sched_setattr",
            Syscall::sched_getattr => "sched_getattr",
            Syscall::renameat2 => "renameat2",
            Syscall::seccomp => "seccomp",
            Syscall::getrandom => "getrandom",
            Syscall::memfd_create => "memfd_create",
            Syscall::kexec_file_load => "kexec_file_load",
            Syscall::bpf => "bpf",
            Syscall::execveat => "execveat",
            Syscall::userfaultfd => "userfaultfd",
            Syscall::membarrier => "membarrier",
            Syscall::mlock2 => "mlock2",
        })
    }
}

struct SyscallVisitor;

impl de::Visitor for SyscallVisitor {
    type Value = Syscall;

    fn visit_str<E: de::Error>(&mut self, v: &str) -> Result<Syscall, E> {
        if let Some(res) = from_str(v) {
            Ok(res)
        } else {
            Err(E::invalid_value(&format!("Unknown Syscall variant: {}", v)))
        }
    }
}

impl Deserialize for Syscall {
    fn deserialize<D: Deserializer>(d: &mut D) -> Result<Syscall, D::Error> {
        d.deserialize_str(SyscallVisitor)
    }
}
